version: "1.0"
web-app-firewall:
  policies:
    - name: "SQL Injection Protection"
      description: "Protect against SQL Injection"
      rules:
        - match:
            request:
              body:
                contains:
                  ["' OR '1'='1", "' OR ''='", "'; DROP", "UNION SELECT", "--"]
              query-string:
                contains:
                  ["' OR '1'='1", "' OR ''='", "'; DROP", "UNION SELECT", "--"]
              headers:
                content-type:
                  ["application/x-www-form-urlencoded", "application/json"]
              methods: ["POST", "GET"]
          action:
            block: true
    - name: "Cross-Site Scripting (XSS) Protection"
      description: "Protect against XSS attacks"
      rules:
        - match:
            request:
              body:
                contains:
                  ["<script>", "<img", "onerror", "alert(", "javascript:"]
              query-string:
                contains:
                  ["<script>", "<img", "onerror", "alert(", "javascript:"]
          action:
            block: true
    - name: "Brute Force Protection"
      description: "Protect against brute force login attempts"
      rules:
        - match:
            request:
              path: "/api/login"
              methods: ["POST"]
          rate-limit:
            requests-per-second: 5
            block-period: 60 # en segundos
  log:
    level: debug
  default-action:
    block: true
