services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ulima2024
      POSTGRES_PASSWORD: root
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  # app:
  #   image: nextjs-app
  #   build:
  #     context: ./
  #     target: dev
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   ports:
  #     - "3000:3000"

volumes:
  postgresql:
  postgresql_data:
